pathconfig:
  #路径最后注意不要漏掉斜杠
  rewardImgsPath: f:/material/rewardImgs/
  advImgPath: f:/material/advImgs/
  shareImgPath: f:/material/shareImgs/
  shareQRImgPath: f:/material/shareQRImgs/
  basicImgPath: f:/material/basicImgs/