spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://db:3306/showpages?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    dbcp2:
          #最小连接数
          min-idle: 5
          #初始化连接数
          initial-size: 5
          #最大连接数
          max-total: 20
          #等待连接最长的超时时间
          max-wait-millis: 200
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

  http:
    encoding:
      charset: utf-8
      enabled: true
    multipart:
      #上传文件大小限制
      max-file-size: 1MB
      max-request-size: 1MB
